### ISSUE TITLE
Copyright Issues

### ISSUE THREAD

**Issue by arctictypo** [dvingerh/fontshop-dl#3]
Hi.
Before we report your account, please remove this repository immediately. You don't own the right to rip the fonts from fontshop.
You may face big charges and up to 4 felonies. So I'm warning you to delete it and don't implement illegal propert theft and no contributing or sharing.

Regards,
Curtis, Fontshop Type Department

**Comment by dvingerh** [comment]
Hello @arctictypo

I understand your grievances, the repository will be inaccessible shortly
Do note that the security flaw regarding web-compatible fonts still exists, the e-mail I sent long ago to report it notwithstanding

**Comment by arctictypo** [comment]
Do you know the total price of the entire products? You don't own the hard work of years of typographers. Charges depend on the damage you did and willing to do. So remove it already. You better read github DMCA guidelines.

**Comment by dvingerh** [comment]
Hello @arctictypo,

The source code file had already been removed and its commit history erased before you sent your reply.
I kept this repository (which receives no visitors at all, by the way) open to be able to inform you the security flaw still exists and to try and learn a bit more about the vague "big charges and 4 felonies" comment but alas.

As for the fact that a previously reported security flaw on your website, which allows font files to be illegally obtained in a few clicks, still exists years later while warning others here of property theft... it is what it is.

Have a nice weekend.

**Comment by arctictypo** [comment]
Yes, sorry i thought it was a good idea to scare you but you know the damage you could make is worth the emergency prevention of stealing, so we have a right to sue you.  Thanks for a quick removal of the repos. Some will be informed about the security vulnerabilities, hope it'll be fixed soon.
